/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.PemesananControl;
import control.KamarControl;
import control.PenghuniControl;
import control.AduanControl;
import java.util.ArrayList;
import model.Pemesanan;
import model.Aduan;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
//import table.TableKamar;

public class Kamar extends javax.swing.JFrame {
    private PemesananControl  psc;
    private KamarControl kc;
    private AduanControl ac;
    private PenghuniControl pc;
    //private TableKamar tk;
    String action = null;
    List<Kamar> listPemesanan;
    List<Kamar> listKamar;
    List<Integer> indexPemesanan = new ArrayList<>();;
    List<Integer> indexKamar = new ArrayList<>();;
    int selectedId = 0;

    /**
     * Creates new form 
     */
    public Kamar() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        psc  = new PemesananControl();
        kc = new KamarControl();
        ac = new AduanControl();
        pc = new PenghuniControl();
        
        
//        showKamar();
//        IDkamarCombobox();
    }
    
    public void setIDkamarCombobox(){
//        listKamar = kc.showListAllKamar();
//        for(int i = 0; i < listKamar.size(); i++){
//            IDkamarCombobox.addItem(listKamar.get(i).getId_kamar());
//            indexKamar.add(i);
//        }
    }
    
    
    public void setEditDeleteBtn(boolean value){
        ubahButton.setEnabled(value);
        hapusButton.setEnabled(value);
        
    }
    
    public void setComponent(boolean value){
        IDkamarCombobox.setEnabled(value);
        KamarPanel.setEnabled(value);
        
        KamarMandiCheckBox.setEnabled(value);
        ACCheckBox.setEnabled(value);
        WIFICheckBox.setEnabled(value);
        
        SaveBtn.setEnabled(value);
        CancelBtn.setEnabled(value);   
    }
    
    public void clearText(){
        IDkamarCombobox.setSelectedItem(ABORT);
        KamarMandiCheckBox.setEnabled(false);
        ACCheckBox.setEnabled(false);
        WIFICheckBox.setEnabled(false);
        
        cariField.setText("");
    }
    
//    public void showKamar(){
//        tableKamar.setModel(kc.showDataKamar(""));
//    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ruanganLabel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        Universitastext = new javax.swing.JLabel();
        NamaUnivText = new javax.swing.JLabel();
        KostText = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        iconPemesanan = new javax.swing.JLabel();
        iconKamar = new javax.swing.JLabel();
        pemesananText = new javax.swing.JLabel();
        penghuniText = new javax.swing.JLabel();
        kamartext = new javax.swing.JLabel();
        AduanText = new javax.swing.JLabel();
        PelanggaranText = new javax.swing.JLabel();
        iconPenghuni = new javax.swing.JLabel();
        iconPelanggaran = new javax.swing.JLabel();
        iconAduan = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        KamarPanel = new javax.swing.JPanel();
        KamarText = new javax.swing.JLabel();
        cariField = new javax.swing.JTextField();
        cariButton = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        idPanel = new javax.swing.JPanel();
        FasilitasText = new javax.swing.JLabel();
        KamarMandiCheckBox = new javax.swing.JCheckBox();
        ACCheckBox = new javax.swing.JCheckBox();
        WIFICheckBox = new javax.swing.JCheckBox();
        idPanel2 = new javax.swing.JPanel();
        IdKamarText = new javax.swing.JLabel();
        IDkamarCombobox = new javax.swing.JComboBox<>();
        idPanel4 = new javax.swing.JPanel();
        StatusText = new javax.swing.JLabel();
        StatusComboBox = new javax.swing.JComboBox<>();
        idPanel5 = new javax.swing.JPanel();
        DeskripsiText = new javax.swing.JLabel();
        idText5 = new javax.swing.JTextField();
        idPanel3 = new javax.swing.JPanel();
        HargaSewaText = new javax.swing.JLabel();
        HargaPanel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        buttonTambah = new javax.swing.JButton();
        ubahButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ruanganLabel.setBackground(new java.awt.Color(255, 255, 255));

        sidebarPanel.setBackground(new java.awt.Color(153, 169, 143));

        Universitastext.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        Universitastext.setForeground(new java.awt.Color(51, 51, 0));
        Universitastext.setText("Atma ");

        NamaUnivText.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        NamaUnivText.setForeground(new java.awt.Color(51, 51, 0));
        NamaUnivText.setText("Jaya");

        KostText.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        KostText.setForeground(new java.awt.Color(51, 51, 0));
        KostText.setText("Kost");

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(KostText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Universitastext)
                .addGap(12, 12, 12)
                .addComponent(NamaUnivText)
                .addContainerGap(962, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(KostText)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Universitastext)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(NamaUnivText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        iconPemesanan.setBackground(new java.awt.Color(153, 204, 0));
        iconPemesanan.setForeground(new java.awt.Color(153, 204, 0));
        iconPemesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/admin.png"))); // NOI18N
        iconPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPemesananMouseClicked(evt);
            }
        });

        iconKamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/kamr.png"))); // NOI18N
        iconKamar.setText("                Data");
        iconKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconKamarMouseClicked(evt);
            }
        });

        pemesananText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pemesananText.setForeground(new java.awt.Color(51, 51, 0));
        pemesananText.setText("Pemesanan");

        penghuniText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        penghuniText.setForeground(new java.awt.Color(51, 51, 0));
        penghuniText.setText("Penghuni");

        kamartext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kamartext.setForeground(new java.awt.Color(51, 51, 0));
        kamartext.setText("Kamar");

        AduanText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AduanText.setForeground(new java.awt.Color(51, 51, 0));
        AduanText.setText("Aduan");

        PelanggaranText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PelanggaranText.setForeground(new java.awt.Color(51, 51, 0));
        PelanggaranText.setText("Pelanggaran");

        iconPenghuni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/penghuni.png"))); // NOI18N
        iconPenghuni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPenghuniMouseClicked(evt);
            }
        });

        iconPelanggaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Pelanggaran.png"))); // NOI18N
        iconPelanggaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPelanggaranMouseClicked(evt);
            }
        });

        iconAduan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/aduan.png"))); // NOI18N
        iconAduan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconAduanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pemesananText))
                    .addComponent(iconPemesanan)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(penghuniText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PelanggaranText)
                                .addComponent(iconPelanggaran, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(9, 9, 9))
                        .addComponent(iconPenghuni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iconAduan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(kamartext))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(AduanText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(iconPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pemesananText)
                .addGap(18, 18, 18)
                .addComponent(iconKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kamartext)
                .addGap(24, 24, 24)
                .addComponent(iconPenghuni, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penghuniText)
                .addGap(30, 30, 30)
                .addComponent(iconAduan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AduanText)
                .addGap(18, 18, 18)
                .addComponent(iconPelanggaran, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PelanggaranText)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(247, 241, 229));

        KamarPanel.setBackground(new java.awt.Color(179, 200, 144));

        KamarText.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        KamarText.setForeground(new java.awt.Color(51, 51, 0));
        KamarText.setText("Kamar");

        cariField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariFieldActionPerformed(evt);
            }
        });

        cariButton.setBackground(new java.awt.Color(214, 232, 219));
        cariButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cariButton.setForeground(new java.awt.Color(51, 51, 0));
        cariButton.setText("Cari");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KamarPanelLayout = new javax.swing.GroupLayout(KamarPanel);
        KamarPanel.setLayout(KamarPanelLayout);
        KamarPanelLayout.setHorizontalGroup(
            KamarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KamarPanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(KamarText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 604, Short.MAX_VALUE)
                .addComponent(cariField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cariButton)
                .addGap(78, 78, 78))
        );
        KamarPanelLayout.setVerticalGroup(
            KamarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KamarPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(KamarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KamarText)
                    .addComponent(cariButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        SaveBtn.setBackground(new java.awt.Color(214, 232, 219));
        SaveBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SaveBtn.setForeground(new java.awt.Color(51, 51, 0));
        SaveBtn.setText("Simpan");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        CancelBtn.setBackground(new java.awt.Color(214, 232, 219));
        CancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CancelBtn.setForeground(new java.awt.Color(51, 51, 0));
        CancelBtn.setText("Batal");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        idPanel.setBackground(new java.awt.Color(214, 232, 219));

        FasilitasText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FasilitasText.setForeground(new java.awt.Color(51, 51, 0));
        FasilitasText.setText("Fasilitas");

        KamarMandiCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        KamarMandiCheckBox.setForeground(new java.awt.Color(51, 51, 0));
        KamarMandiCheckBox.setText("Kamar Mandi Dalam");
        KamarMandiCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KamarMandiCheckBoxActionPerformed(evt);
            }
        });

        ACCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ACCheckBox.setForeground(new java.awt.Color(51, 51, 0));
        ACCheckBox.setText("AC");
        ACCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACCheckBoxActionPerformed(evt);
            }
        });

        WIFICheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WIFICheckBox.setForeground(new java.awt.Color(51, 51, 0));
        WIFICheckBox.setText("WIFI");

        javax.swing.GroupLayout idPanelLayout = new javax.swing.GroupLayout(idPanel);
        idPanel.setLayout(idPanelLayout);
        idPanelLayout.setHorizontalGroup(
            idPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(idPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idPanelLayout.createSequentialGroup()
                        .addComponent(KamarMandiCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(ACCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WIFICheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FasilitasText))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        idPanelLayout.setVerticalGroup(
            idPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(FasilitasText)
                .addGap(18, 18, 18)
                .addGroup(idPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KamarMandiCheckBox)
                    .addComponent(ACCheckBox)
                    .addComponent(WIFICheckBox))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        idPanel2.setBackground(new java.awt.Color(214, 232, 219));

        IdKamarText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IdKamarText.setForeground(new java.awt.Color(51, 51, 0));
        IdKamarText.setText("ID Kamar");

        IDkamarCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDkamarComboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idPanel2Layout = new javax.swing.GroupLayout(idPanel2);
        idPanel2.setLayout(idPanel2Layout);
        idPanel2Layout.setHorizontalGroup(
            idPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(idPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDkamarCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdKamarText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idPanel2Layout.setVerticalGroup(
            idPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(IdKamarText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDkamarCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        idPanel4.setBackground(new java.awt.Color(214, 232, 219));

        StatusText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StatusText.setForeground(new java.awt.Color(51, 51, 0));
        StatusText.setText("Status");

        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));
        StatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idPanel4Layout = new javax.swing.GroupLayout(idPanel4);
        idPanel4.setLayout(idPanel4Layout);
        idPanel4Layout.setHorizontalGroup(
            idPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(idPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idPanel4Layout.setVerticalGroup(
            idPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(StatusText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        idPanel5.setBackground(new java.awt.Color(214, 232, 219));

        DeskripsiText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeskripsiText.setForeground(new java.awt.Color(51, 51, 0));
        DeskripsiText.setText("Deskripsi");

        idText5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idText5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idPanel5Layout = new javax.swing.GroupLayout(idPanel5);
        idPanel5.setLayout(idPanel5Layout);
        idPanel5Layout.setHorizontalGroup(
            idPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(idPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeskripsiText)
                    .addComponent(idText5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idPanel5Layout.setVerticalGroup(
            idPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(DeskripsiText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        idPanel3.setBackground(new java.awt.Color(214, 232, 219));

        HargaSewaText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HargaSewaText.setForeground(new java.awt.Color(51, 51, 0));
        HargaSewaText.setText("Harga Sewa");

        HargaPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idPanel3Layout = new javax.swing.GroupLayout(idPanel3);
        idPanel3.setLayout(idPanel3Layout);
        idPanel3Layout.setHorizontalGroup(
            idPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(idPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HargaSewaText)
                    .addComponent(HargaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idPanel3Layout.setVerticalGroup(
            idPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(HargaSewaText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HargaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Kamar", "Fasilitas", "Harga Sewa", "Deskripsi", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(179, 200, 144));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        buttonTambah.setBackground(new java.awt.Color(214, 232, 219));
        buttonTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonTambah.setForeground(new java.awt.Color(51, 51, 0));
        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        ubahButton.setBackground(new java.awt.Color(214, 232, 219));
        ubahButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ubahButton.setForeground(new java.awt.Color(51, 51, 0));
        ubahButton.setText("Ubah");
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });

        hapusButton.setBackground(new java.awt.Color(214, 232, 219));
        hapusButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hapusButton.setForeground(new java.awt.Color(51, 51, 0));
        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ubahButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(buttonTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ubahButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hapusButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(456, 456, 456)
                        .addComponent(SaveBtn)
                        .addGap(18, 18, 18)
                        .addComponent(CancelBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(KamarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 744, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(KamarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SaveBtn)
                                .addComponent(CancelBtn)))))
                .addGap(83, 83, 83))
        );

        jScrollPane2.setViewportView(jPanel1);

        jScrollPane4.setViewportView(jScrollPane2);

        javax.swing.GroupLayout ruanganLabelLayout = new javax.swing.GroupLayout(ruanganLabel);
        ruanganLabel.setLayout(ruanganLabelLayout);
        ruanganLabelLayout.setHorizontalGroup(
            ruanganLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ruanganLabelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ruanganLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(ruanganLabelLayout.createSequentialGroup()
                        .addGroup(ruanganLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1835, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        ruanganLabelLayout.setVerticalGroup(
            ruanganLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ruanganLabelLayout.createSequentialGroup()
                .addGroup(ruanganLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ruanganLabelLayout.createSequentialGroup()
                        .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ruanganLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ruanganLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        // TODO add your handling code here:
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
                                            
        clearText();
        //showKamar();
        setComponent(false);
        setEditDeleteBtn(false);
    
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        setComponent(true);
        clearText();
        action = "addKamar";
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        //tableKamar.setModel(kc.showDataKamar(cariField.getText()));
    }//GEN-LAST:event_cariButtonActionPerformed

    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahButtonActionPerformed
        setComponent(true);
        action = "editKamar";
    }//GEN-LAST:event_ubahButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        kc.deleteDataKamar(selectedId);
        clearText();
        //showKamar();
        setComponent(false);
        setEditDeleteBtn(false);
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void cariFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariFieldActionPerformed

    private void ACCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ACCheckBoxActionPerformed

    private void HargaPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaPanelActionPerformed

    private void idText5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idText5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idText5ActionPerformed

    private void IDkamarComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDkamarComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDkamarComboboxActionPerformed

    private void KamarMandiCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KamarMandiCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KamarMandiCheckBoxActionPerformed

    private void StatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusComboBoxActionPerformed

    private void iconPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPemesananMouseClicked
        // TODO add your handling code here:
//        Pemesanan pv = new PemesananView();
//        this.dispose();
//        pv.setVisible(true);
    }//GEN-LAST:event_iconPemesananMouseClicked

    private void iconKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconKamarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconKamarMouseClicked

    private void iconPenghuniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPenghuniMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconPenghuniMouseClicked

    private void iconAduanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAduanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconAduanMouseClicked

    private void iconPelanggaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPelanggaranMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconPelanggaranMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ACCheckBox;
    private javax.swing.JLabel AduanText;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JLabel DeskripsiText;
    private javax.swing.JLabel FasilitasText;
    private javax.swing.JTextField HargaPanel;
    private javax.swing.JLabel HargaSewaText;
    private javax.swing.JComboBox<String> IDkamarCombobox;
    private javax.swing.JLabel IdKamarText;
    private javax.swing.JCheckBox KamarMandiCheckBox;
    private javax.swing.JPanel KamarPanel;
    private javax.swing.JLabel KamarText;
    private javax.swing.JLabel KostText;
    private javax.swing.JLabel NamaUnivText;
    private javax.swing.JLabel PelanggaranText;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JLabel StatusText;
    private javax.swing.JLabel Universitastext;
    private javax.swing.JCheckBox WIFICheckBox;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton cariButton;
    private javax.swing.JTextField cariField;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel iconAduan;
    private javax.swing.JLabel iconKamar;
    private javax.swing.JLabel iconPelanggaran;
    private javax.swing.JLabel iconPemesanan;
    private javax.swing.JLabel iconPenghuni;
    private javax.swing.JPanel idPanel;
    private javax.swing.JPanel idPanel2;
    private javax.swing.JPanel idPanel3;
    private javax.swing.JPanel idPanel4;
    private javax.swing.JPanel idPanel5;
    private javax.swing.JTextField idText5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel kamartext;
    private javax.swing.JLabel pemesananText;
    private javax.swing.JLabel penghuniText;
    private javax.swing.JPanel ruanganLabel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton ubahButton;
    // End of variables declaration//GEN-END:variables
}
